variables:
  CONAN_REFERENCE: "winiconv/0.0.8"
  CONAN_USERNAME: "fw4spl"
  CONAN_LOGIN_USERNAME: "fw4spl"
  CONAN_CHANNEL: "stable"
  CONAN_UPLOAD: "http://5.39.78.163:8081/artifactory/api/conan/conan-local"
  CONAN_STABLE_BRANCH_PATTERN: "stable/*"
  CONAN_UPLOAD_ONLY_WHEN_STABLE: 1 # Will only upload when the branch matches "stable/*"
  CONAN_DOCKER_32_IMAGES: 1

stages:
  - build

windows-msvc2017:
  image: greenjava/vcbuild2017:1.0
  stage: build
  script:
    - python build.py
  tags:
    - docker
    - windows
    - msvc2017
